#+title: maf

* Guides and Conventions
  A command should take an explicit number of arguments - never implicit.

  For example, (my/calc-factor-by) by default works on the top 2 stack items.
  But for convenience, we may want it to to automatically take the GCD of the
  top stack item if no second argument is given.

  However, this would be a mistake. In order for (my/calc-factor-by) to work in
  context properly, it *cannot* accept an implicit number of arguments.

  Take an example where the point is over a subexpression at stack level m=3.
  The user invokes (my/calc-factor-by) to factor the subexpression. Should the
  subexpression factor by its GCD or by the stack (m=1) item? Both cases are
  valid and useful, but the choice cannot be disambiguated.

  The correct behavior is for the command to either *always* take 2 arguments
  (the target expression and the factor) or *always* take a single argument (the
  target expression - the GCD is automatically selected as the factor).

  If the first behavior is chosen, the `H` flag can be used to *explicitly*
  enable the second behavior. This is the preferred way.

* Docs
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Lisp-Definitions][lisp definitions]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Stack-Access][stack access]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Symbolic-Lisp-Functions][symbolic lisp functions]]

* Plan
  I want to move all of the calc customizations in @my/calc/ into a new package
  called "maf". How should we go about this? I want to make as few changes as
  possible. Just relocate. Some other things:
  - Also create a minor-mode package.
  - This package should be its own git project (how to handle this?)

* Steps
  1) Organize .org file
  2) Write macro first then develop maf-test based on the various option
     combinations and input types (expression, line, equation, etc)
  3) Develop maf-test
  4) Read calc manual

* Todo [0/31]
  - [ ] Add function to get calc buffer
  - [ ] If on home line, stick point to the "."
  - [ ] Replace noun with digit entry if point is on sub-formula
  - [ ] Remove keep-point flag in macro
  - [ ] Add plus and minus calc functions
  - [ ] Add sin/cos/tan and inverse functions.
  - [ ] Also "stick" point to beginning or end of entry's expression. and also over =, !=, <=/=>
  - [ ] When point is over equation symbol, operate on both sides (unless map is -1).
  - [ ] k k (my/calc-evaluate N) should work on fractions and division.
  - [ ] g i (my/calc-graph-quick-with-range) interval form a:b should work with spaces 'a b'
  - [ ] (calc-fraction ARG) and calc-float should work contextually.
  - [ ] (my/calc-factor-by-gcd) should factor out negative numbers (leave the
    leading term in the binomial positive).
  - [ ] Make (my/calc-sel-negate) contextual.
  - [ ] Should have a form to collect the numerator.
    3:2 sqrt(2) -> 3 sqrt(2) / 2
  - [ ] S-up/down should toggle +/-, ln/e, */, log/^, etc.
  - [ ] Take: y = 1:2 - (5 x - 5 k)^-2 / 2 and represent the negative power as a reciprocal.
  - [ ] (my/calc-quick-variable) should be contextual.
  - [ ] ( and ) should move to next opening/closing paren.
  - [ ] (my/calc-collect-fractions) -> 16:3 x / 1
  - [ ] Line option (calc-option &optional N) should be bound to single key without modifiers.
  - [ ] (my/calc-log-exp-rules) on line should transform entire line.
  - [ ] Binary arity functions should noop on targeting sub-formula at stack=1.
    They have nowhere to take args from.
  - [ ] If command is line-target, then m=2 is the subject and m=1 is the arg,
    same as if point were at home.
  - [ ] Remove `m` parameter. Always take args from stack. New options dictate
    how many options.
  - [ ] Only allow unary and binary commands.
  - [ ] Add command to isolate current sub-formula on current side of equation.
  - [ ] l F (my/calc-factor-by-gcd) should prefer negative value in factor.
  - [ ] Full formula buffer should have "recents" section.
  - [ ] Saved formulas should support "notes" that display in full formula buffer.
  - [ ] TAB command to swap lines should work contextually.
  - [ ] a a (calc-apart) should work contextually.

* Notes
  - Try to use (defmath) macro if possible.

* Main features
  - Make edit-mode obsolete. Implement free-edit-mode, like editing a dired buffer.

* Bugs
  - (my/calc-factor-by-gcd) not working
  - Some commands like * and / don't work in "prefix" area on home line.
    # Found the issue: when you enter 3 * or some other operation, we prevent
    # point from moving so make it easier to operate on lines. However this
    # means that when the digit is entered, point is still on the entry line, so
    # the stack item is being multiplied by itself, then replaced.
  - `saved-point-is-at-home` is nil when it should be true when a binary command
    is invoked at the first column of the home row because (calc-align-stack-window)
    is being repressed.

    This is hard to accommodate for because the macro doesn't run until the
    digit is already pushed to the stack. By that time, point is on line 1
    instead of home.

    Why is point behaving differently in column 1 vs column 2?
  - (my/calc-factor-by-gcd) only works properly on the home line or a duplicated
    value on the home line. It's choosing a different factor on (cplx)-style numbers.
  - (my/calc-commute) doesn't flip the inequality.
    x > 1
    (my/calc-commute)
    1 > x
  - (my/calc-commute) doesn't work properly. It doesn't keep the equation
    balanced.
  - Equal command doesn't work with point on line 1, but works on home.
** BUG: (my/calc-factor-by-gcd) on `x y - 2 x` isn't working.
   BUG: 3 y - 24
** BUG (my/calc-backward-noun) and (my/calc-forward-noun) should ignore line prefix.

* Issues
  - C-g leaves and moves point to home instead of leaving digit entry and retaining point.

* BACKLOG
** Issue: j D (my/calc-sel-distribute)
   Doesn't work contextually. Should work like 'j M'. Work on stack item when at home.
** Instead of having to use the default bindings 'a m &', can you make 'a m o' work?
   This should invert both sides of an equation. Normally the binding would use
   '&' instead of 'o', but 'o' is more convenient and I have that bound to
   'calc-inv' The issue is that the 'a m' sequence expects standard keybindings.
** Flatten conditions
   : Not worth it. Makes the code more complicated actually.
   (my/calc-replace-expr-dwim)
   Flatten the conditions for clarity without duplicating code.

* Highlighting
  - in selection mode, highlight the selection
  - highlight both sides of equation separately with different colors

* Major features
  Vim bindings (noun, verb, char)
  Persistent sub-formula highlighting
  Debug modes

* Package
  Binding for "home"
  Args buffer
  Config file with all config settings and default values
   calx: calc with alternative ux
  How to use macro with def math
  Alternative graphing
  Alternative trail. Should support time travel and finding old single entries.
  Use transient mode for prefix commands
  Swap _ and -
  Show all formulas buffer

* Debug
  - Debug to print. Show display representation and debug representation.

* Questions
  - Should stack should be normal numbers? Only encased when necessary?
  - Are new entries plain or cplx numbers?
  - How does restore-calc-stack work? Does it store as atoms or cplx?
  - When restored, are the cplx numbers still unique?

* Musings
  - Do we need a difference / conciliation engine?

* Refactor
  - Plain object instead of struct [?]
  - In push, use return value instead of replace function?
  - What would a functional programming approach look like?
  - Data based, refactor as much into pure functions as possible, the replace
    function, point restoration. Only apply effects at the end.
