;; -*- lexical-binding: t; -*-
;;
;; Functional sketch -- companion to lib-refactor-sketch.el.
;;
;; Same problem (refactor `my/calc-replace-expr-dwim'), different stance:
;; the whole pipeline is data-in / data-out with side effects isolated
;; to a single apply step. Compare with lib-refactor-sketch.el, which
;; keeps an imperative `(replace X)' inside BODY and lets a closure mutate
;; the stack on the spot.
;;
;; ============================================================================
;; PIPELINE
;; ============================================================================
;;
;;   1. capture     :: () -> CURSOR-STATE        (pure read of point/state)
;;   2. resolve     :: () -> TARGET              (pure read of point/stack)
;;   3. body        :: EXPR ARG -> NEW-EXPR      (caller's logic; pure value)
;;   4. compute-plan:: TARGET BODY OPTS -> PLAN  (calls body 1-2x, no I/O)
;;   5. apply-plan  :: PLAN -> ()                (THE one stack mutation site)
;;   6. restore     :: CURSOR-STATE -> ()        (restore the cursor)
;;
;; my/calc-push is the small orchestrator that wires (2)..(5).
;; The defun shell generated by `my/defcmd' wraps it with (1) and (6).
;;
;; ============================================================================
;; HOW BODY-FN DIFFERS FROM THE IMPERATIVE SKETCH
;; ============================================================================
;;
;; lib-refactor-sketch.el: body is invoked with a `replace' closure that
;; performs the stack mutation as a side effect. BODY's return value is
;; discarded; what matters is whether/how `replace' was called.
;;
;; This file: body is a pure function from (expr, arg) to the new
;; expression to push. No `replace'. To "leave the target unchanged"
;; just return EXPR; to push a different value, return that value.
;;
;; Examples speak loudest:
;;
;;   ;; imperative
;;   (my/defcmd my/calc-factor (expr replace)
;;     :prefix "fctr"
;;     (replace (calcFunc-factor expr)))
;;
;;   ;; functional
;;   (my/defcmd my/calc-factor (expr)
;;     :prefix "fctr"
;;     (calcFunc-factor expr))
;;
;; The user-facing BINDINGS list loses `replace'. The body's value IS
;; the new expression.
;;
;; ============================================================================
;; WHAT YOU GAIN AND LOSE
;; ============================================================================
;;
;; Gain:
;;   - compute-plan is testable with no calc buffer (data in, data out).
;;   - Every stack mutation flows through apply-plan -- single audit point.
;;   - Symmetric with cursor: capture / decide / apply, three steps,
;;     each side-effect-free except the final apply.
;;   - BODY is a plain function. Easy to unit-test independently.
;;
;; Lose:
;;   - BODY can no longer do multi-step side effects ("push X, then pop").
;;     If you need that, you're outside my/defcmd; call apply-plan
;;     directly or use the imperative sketch.
;;   - PLAN becomes a stable internal data shape; adding a new kind
;;     touches both compute-plan and apply-plan instead of just one helper.
;;   - The macro layer in `my/defcmd' shrinks (no cl-flet for `replace');
;;     in return the dispatch grows.


;;; ===========================================================================
;;; Target struct + resolver
;;; ===========================================================================
;;
;; Identical in shape to lib-refactor-sketch.el. Reproduced here so the
;; file stands alone.

(cl-defstruct my/calc--target
  kind             ; 'selection | 'subexpr | 'entry | 'home | 'equation
  m                ; stack level (1=top)
  expr             ; what BODY sees as its EXPR argument
  parent-formula   ; full formula at stack[m] for selection/subexpr; nil otherwise
  rel-op           ; relational operator symbol (equation only)
  lhs rhs)         ; the two sides of the relation (equation only)

(defun my/calc--target-at-point (opt-m opt-line equation-map?)
  "Inspect point and calc state; return a `my/calc--target'.
OPT-M is the stack level for the home case (1 or 2 in practice).
OPT-LINE non-nil forces whole-line targeting.
EQUATION-MAP? non-nil lets relations be classified as 'equation."
  (cond
   ((my/calc-active-selection-p)
    (let* ((m (my/calc-active-entry-m-dwim))
           (entry (nth m calc-stack)))
      (make-my/calc--target :kind 'selection :m m
                            :expr (nth 2 entry)
                            :parent-formula (car entry))))
   ((my/calc-point-is-at-home-p)
    (make-my/calc--target :kind 'home :m opt-m
                          :expr (car (calc-top opt-m 'entry))))
   (t
    (let* ((m (calc-locate-cursor-element (point)))
           (full (car (nth m calc-stack)))
           (line? (or opt-line calc-option-flag))
           (sub (and (not line?)
                     (not (eolp))
                     (not (my/calc-point-is-in-line-prefix-p))
                     (my/calc-subformula-at-point)))
           (rel (and equation-map? (null sub) (my/calc-rel-op-p full))))
      (cond
       (sub (make-my/calc--target :kind 'subexpr :m m
                                  :expr sub :parent-formula full))
       (rel (make-my/calc--target :kind 'equation :m m
                                  :expr full :rel-op rel
                                  :lhs (nth 1 full) :rhs (nth 2 full)))
       (t   (make-my/calc--target :kind 'entry :m m :expr full)))))))


;;; ===========================================================================
;;; Cursor state (functional)
;;; ===========================================================================
;;
;; Capture and restore as plain functions. No macro wrapper. Called
;; explicitly by `my/defcmd''s generated defun (and by hand-written
;; commands like `my/calc-expand').

(cl-defstruct my/calc--cursor-state
  point line col-pos at-home sel-active keep-args)

(defun my/calc--capture-cursor-state ()
  "Snapshot pre-operation cursor + flag state."
  (make-my/calc--cursor-state
   :point      (point)
   :line       (line-number-at-pos)
   :col-pos    (cond ((eolp) 'eol)
                     ((my/calc-point-is-in-line-prefix-p) 'bol))
   :at-home    (my/calc-point-is-at-home-p)
   :sel-active (my/calc-active-selection-p)
   :keep-args  calc-keep-args-flag))

(defun my/calc--restore-cursor (s)
  "Restore point per cursor-state S."
  (pcase-let (((cl-struct my/calc--cursor-state
                          point line col-pos at-home sel-active keep-args)
               s))
    (cond
     (sel-active
      (goto-char point))
     ((or keep-args at-home)
      (calc-align-stack-window))
     (t
      (goto-char point)
      (when (/= (line-number-at-pos) line)
        (goto-char (point-min))
        (forward-line (1- line)))
      (pcase col-pos
        ('eol (end-of-line))
        ('bol (beginning-of-line)))))))


;;; ===========================================================================
;;; Plans (data shapes for stack updates)
;;; ===========================================================================
;;
;; A PLAN is one of:
;;
;;   (push     M PREFIX FORMULA)
;;     Replace stack[M] with FORMULA. Log PREFIX in the trail.
;;
;;   (push-sel M PREFIX FORMULA SUBEXPR)
;;     Like push, but mark SUBEXPR as the new selection (so calc can
;;     re-select the equivalent sub-expression after the update).
;;
;;   (push-eq  M PREFIX OP LHS RHS)
;;     Push the relation (OP LHS RHS) at stack[M].
;;
;; Any plan may be followed by a separate POP step (binary commands):
;; that's handled by wrapping the plan in a (plan-then-pop PLAN N) form:
;;
;;   (then-pop PLAN N)
;;     Apply PLAN, then `(calc-pop-stack N)'.
;;
;; The plan is plain Lisp data -- inspectable, loggable, testable.


;;; ===========================================================================
;;; compute-plan (pure)
;;; ===========================================================================
;;
;; Calls BODY-FN one (or two, for equation) times to obtain the new
;; expression(s). Returns a plan describing the stack update.

(defun my/calc--run-body (body-fn expr arg-val simp)
  "Invoke BODY-FN on EXPR and ARG-VAL, honoring `:simp -1'."
  (if (eq simp -1)
      (my/calc-without-simplification (funcall body-fn expr arg-val))
    (funcall body-fn expr arg-val)))

(defun my/calc--compute-plan (body-fn tgt arg-val binary? prefix simp)
  "Pure: TARGET + BODY -> PLAN.
Wraps the plan in `(then-pop PLAN 1)' when BINARY? is non-nil."
  (let* ((kind (my/calc--target-kind tgt))
         (m    (my/calc--target-m tgt))
         (plan
          (pcase kind
            ('equation
             (let* ((op  (my/calc--target-rel-op tgt))
                    (lhs (my/calc--target-lhs tgt))
                    (rhs (my/calc--target-rhs tgt))
                    (new-lhs (my/calc--run-body body-fn lhs arg-val simp))
                    (new-rhs (my/calc--run-body body-fn rhs arg-val simp)))
               (list 'push-eq m prefix op new-lhs new-rhs)))

            ('selection
             (let* ((expr (my/calc--target-expr tgt))
                    (parent (my/calc--target-parent-formula tgt))
                    (new-expr (my/calc--run-body body-fn expr arg-val simp))
                    (new-formula (calc-replace-sub-formula parent expr new-expr)))
               (list 'push-sel m prefix new-formula new-expr)))

            ('subexpr
             (let* ((expr (my/calc--target-expr tgt))
                    (parent (my/calc--target-parent-formula tgt))
                    (new-expr (my/calc--run-body body-fn expr arg-val simp))
                    (new-formula (calc-replace-sub-formula parent expr new-expr)))
               (list 'push m prefix new-formula)))

            ('entry
             (let* ((expr (my/calc--target-expr tgt))
                    (new-expr (my/calc--run-body body-fn expr arg-val simp)))
               (list 'push m prefix new-expr)))

            ('home
             (let* ((expr (my/calc--target-expr tgt))
                    (new-expr (my/calc--run-body body-fn expr arg-val simp))
                    ;; In calc-keep-args mode, results push at level 1.
                    (effective-m (if calc-keep-args-flag 1 m)))
               (list 'push effective-m prefix new-expr)))

            (k (error "Unknown target kind: %s" k)))))
    (if binary? (list 'then-pop plan 1) plan)))


;;; ===========================================================================
;;; apply-plan (the ONE side-effecting function)
;;; ===========================================================================

(defun my/calc--apply-plan (plan wrap)
  "Apply PLAN to the calc stack. WRAP=t wraps in `calc-wrapper'."
  (let ((thunk (lambda () (my/calc--apply-plan-1 plan))))
    (if wrap (calc-wrapper (funcall thunk)) (funcall thunk))))

(defun my/calc--apply-plan-1 (plan)
  "Internal: apply PLAN's effects. Does not wrap with calc-wrapper."
  (pcase plan
    (`(push ,m ,prefix ,formula)
     (calc-pop-push-record-list 1 prefix formula m))

    (`(push-sel ,m ,prefix ,formula ,subexpr)
     (calc-pop-push-record-list 1 prefix formula m subexpr))

    (`(push-eq ,m ,prefix ,op ,lhs ,rhs)
     (calc-pop-push-record-list 1 prefix (list op lhs rhs) m))

    (`(then-pop ,inner ,n)
     (my/calc--apply-plan-1 inner)
     (when (> n 0) (calc-pop-stack n)))

    (other (error "Unknown plan shape: %s" other))))


;;; ===========================================================================
;;; Dispatch orchestrator
;;; ===========================================================================
;;
;; Tiny. Wires resolver -> compute-plan -> apply-plan.

(cl-defun my/calc-push (body-fn &key
                                (binary? nil)
                                (prefix "")
                                (wrap t)
                                (simp nil)
                                (map? t)
                                (line? nil))
  "Run BODY-FN against the dwim-resolved calc target.
BODY-FN must have signature (lambda (EXPR ARG) NEW-EXPR).
See file header for the pipeline shape.

This function does NOT preserve point. Wrap the call with
`my/calc--capture-cursor-state' + `my/calc--restore-cursor'."
  (let* ((m (if binary? 2 1))
         (arg-val (when binary?
                    (my/calc-without-simplification (calc-top-n 1))))
         (tgt (my/calc--target-at-point m line? (not (eq map? -1))))
         (plan (my/calc--compute-plan body-fn tgt arg-val binary? prefix simp)))
    (my/calc--apply-plan plan wrap)))


;;; ===========================================================================
;;; my/defcmd (user-facing macro)
;;; ===========================================================================
;;
;; The macro's only job is ergonomics:
;;   - Validate BINDINGS at expansion time.
;;   - Peel an optional docstring and collect `:keyword VALUE' pairs.
;;   - Generate a `defun' that captures cursor state, runs the dispatch,
;;     restores cursor.
;;
;; BINDINGS surface is now `(expr arg)' -- no `replace', because body
;; returns a value.

(defconst my/defcmd--known-bindings '(expr arg)
  "Names callable inside BODY: `expr' and `arg' (binary only).")

(defconst my/defcmd--known-options
  '(:prefix :wrap :simp :map? :line?)
  "Option keywords accepted by `my/defcmd'.")

(defun my/defcmd--validate-bindings (bindings name)
  (let ((unknown (cl-set-difference bindings my/defcmd--known-bindings)))
    (when unknown
      (error "Unknown binding(s) in my/defcmd %s: %s" name unknown))))

(defun my/defcmd--parse-rest (rest name)
  "Return (DOCSTRING OPTS BODY) by parsing the after-BINDINGS tail."
  (let ((docstring (and (stringp (car rest)) (cdr rest) (pop rest)))
        (opts nil))
    (while (keywordp (car rest))
      (let ((k (pop rest))
            (v (pop rest)))
        (push (cons k v) opts)))
    (let ((unknown (cl-set-difference (mapcar #'car opts)
                                      my/defcmd--known-options)))
      (when unknown
        (error "Unknown option(s) in my/defcmd %s: %s" name unknown)))
    (list docstring opts rest)))

(defmacro my/defcmd (name bindings &rest rest)
  "Define a no-arg interactive calc command NAME.

BINDINGS is a subset of `(expr arg)'; presence of `arg' makes the
command BINARY (m=2, top stack item bound to ARG, one auto-pop).

After BINDINGS comes an optional docstring, then `:keyword VALUE'
pairs, then BODY. BODY is a function from (EXPR, ARG) to the new
expression to push; multiple body forms are wrapped in an implicit
`progn' so the last form's value is what gets pushed."
  (declare (indent 2) (doc-string 3))
  (my/defcmd--validate-bindings bindings name)
  (seq-let (docstring opts body) (my/defcmd--parse-rest rest name)
    (let* ((binary? (memq 'arg bindings))
           (sym-expr (if (memq 'expr bindings) 'expr (gensym "_unused-expr-")))
           (sym-arg  (if (memq 'arg  bindings) 'arg  (gensym "_unused-arg-"))))
      `(defun ,name ()
         ,@(when docstring (list docstring))
         (interactive)
         (let ((cs (my/calc--capture-cursor-state)))
           (my/calc-push
            (lambda (,sym-expr ,sym-arg) ,@body)
            :binary?   ,(if binary? t nil)
            :prefix    ,(alist-get :prefix opts "")
            :wrap      ,(alist-get :wrap   opts t)
            :simp      ,(alist-get :simp   opts nil)
            :map?      ,(alist-get :map?   opts t)
            :line?     ,(alist-get :line?  opts nil))
           (my/calc--restore-cursor cs))))))


;;; ===========================================================================
;;; Examples
;;; ===========================================================================
;;
;; ---------------------------------------------------------------------------
;; Example 1: unary -- body returns the new expression.
;; ---------------------------------------------------------------------------
;;
;;   (my/defcmd my/calc-factor (expr)
;;     "Factor the active selection or whole stack entry at point."
;;     :prefix "fctr"
;;     (calcFunc-factor expr))
;;
;; ---------------------------------------------------------------------------
;; Example 2: binary -- `arg' is the top stack item; body returns new value.
;; ---------------------------------------------------------------------------
;;
;;   (my/defcmd my/calc-factor-by (expr arg)
;;     "Factor the target expression by the top stack item."
;;     :prefix "fctr"
;;     :simp -1
;;     (let* ((divided (-> (calcFunc-div expr arg)
;;                         calcFunc-expand calcFunc-nrat
;;                         calcFunc-expand math-simplify)))
;;       (calcFunc-mul arg divided)))
;;
;; ---------------------------------------------------------------------------
;; Example 3: prefix-arg command -- hand-written, calls dispatch directly.
;; ---------------------------------------------------------------------------
;;
;;   (defun my/calc-expand (n)
;;     "Expand the active selection, sub-formula at point, or top stack entry.
;;   With numeric prefix N, expand only N levels deep."
;;     (interactive "P")
;;     (let ((cs (my/calc--capture-cursor-state)))
;;       (my/calc-push
;;        (lambda (expr _arg)
;;          (if n (calcFunc-expand expr (prefix-numeric-value n))
;;            (calcFunc-expand expr)))
;;        :prefix "expa")
;;       (my/calc--restore-cursor cs)))


;; (provide 'my/calc/lib-refactor-functional)
