#+title: maf

* Docs
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Lisp-Definitions][lisp definitions]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Stack-Access][stack access]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Symbolic-Lisp-Functions][symbolic lisp functions]]

* Plan (macro)
  1) [ ] Move all of relevant my/calc config into project.

* Major features
  - [ ] Vim bindings (noun, verb, char)
  - [X] Persistent sub-formula highlighting
  - [ ] Debug modes
  - [ ] Make edit-mode obsolete. Implement free-edit-mode, like editing a dired buffer.
  - [ ] Submodules: graphing submodule, vim bindings submodule, etc. Toggle on to
    enable a section of features.

* IN-PROGRESS Todo
  - [X] Write command bound to S-up/down that toggles operators: + and -, ln and e, * and /, log and ^, etc.
  - [ ] Replace noun with digit entry if point is on sub-formula
  - [ ] TAB command to swap lines should work contextually.
  - [ ] a a (calc-apart) should work contextually.
** Later
   - [ ] k k (my/calc-evaluate N) should work on fractions and division.
   - [ ] g i (my/calc-graph-quick-with-range) interval form a:b should work with spaces 'a b'
   - [ ] Full formula buffer should have "recents" section.
   - [ ] Saved formulas should support "notes" that display in full formula buffer.
   - [ ] Add command to move to parent expression.
     1:  y = 2 (x| + 3)^2 - 12
     ->  y = 2 (x + 3)|^2 - 12
   - [ ] Distribute and merge should operate contextually.
   - [ ] Always show entry at point in "big" mode, somewhere.
   - [ ] Move all options to unified configuration view.
     - Free up option prefix bindings (eg, m).
   - [ ] Rebind +, -, negate, negative commands. Since these are used very
     frequently, make them easily accessible.
   - [ ] Feature: In stack mode, bind M-[n/p] to recall previous/next bare
     (starting from empty) edit-mode entries. The purpose of this is to avoid the
     pattern of having to duplicate or store an entry that you might want to
     reuse or recall in case you screw up a calculation.

* Port
  - [ ] Port my/calc/* features one-by-one.

* Bugs
  - Some commands like * and / don't work in "prefix" area on home line.
    # Found the issue: when you enter 3 * or some other operation, we prevent
    # point from moving so make it easier to operate on lines. However this
    # means that when the digit is entered, point is still on the entry line, so
    # the stack item is being multiplied by itself, then replaced.
  - `saved-point-is-at-home` is nil when it should be true when a binary command
    is invoked at the first column of the home row because (calc-align-stack-window)
    is being repressed.

    This is hard to accommodate for because the macro doesn't run until the
    digit is already pushed to the stack. By that time, point is on line 1
    instead of home.

    Why is point behaving differently in column 1 vs column 2?
  - Equal command doesn't work with point on line 1, but works on home.
** BUG (my/calc-backward-noun) and (my/calc-forward-noun) should ignore line prefix.

* Issues
  - C-g leaves and moves point to home instead of leaving digit entry and retaining point.

* BACKLOG
** Issue: j D (my/calc-sel-distribute)
   Doesn't work contextually. Should work like 'j M'. Work on stack item when at home.
** Instead of having to use the default bindings 'a m &', can you make 'a m o' work?
   This should invert both sides of an equation. Normally the binding would use
   '&' instead of 'o', but 'o' is more convenient and I have that bound to
   'calc-inv' The issue is that the 'a m' sequence expects standard keybindings.

* Package
  Binding for "home"
  Args buffer
  Config file with all config settings and default values
   calx: calc with alternative ux
  How to use macro with def math
  Alternative graphing
  Alternative trail. Should support time travel and finding old single entries.
  Use transient mode for prefix commands
  Swap _ and -
  Show all formulas buffer


* Cleanup
  - [ ] Delete my/calc
