#+title: maf

* Docs
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Lisp-Definitions][lisp definitions]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Stack-Access][stack access]]
  [[https://www.gnu.org/software/emacs/manual/html_mono/calc.html#Symbolic-Lisp-Functions][symbolic lisp functions]]

* Plan (macro)
  1) [ ] Move all of relevant my/calc config into project.

* Major features
  - [ ] Vim bindings (noun, verb, char)
  - [X] Persistent sub-formula highlighting
  - [ ] Submodules: graphing submodule, vim bindings submodule, etc. Toggle on to
    enable a section of features.

* Port
  - [ ] Port my/calc/* features one-by-one.


   - [ ] maf-edit: indent on newline and stamp prefix

* IN-PROGRESS Todo
  - [ ] maf: For custom commands, write docstrings with descriptions and examples. Settle on a
    docstring convention.
    - description
    - examples
    - what else?
** Later
   - [ ] Snapshot after every commit. Navigate through history in history
     navigator.
   - [ ] k k (my/calc-evaluate N) should work on fractions and division.
   - [ ] g i (my/calc-graph-quick-with-range) interval form a:b should work with spaces 'a b'
   - [ ] Full formula buffer should have "recents" section.
   - [ ] Saved formulas should support "notes" that display in full formula buffer.
   - [ ] Add command to move to parent expression.
     1:  y = 2 (x| + 3)^2 - 12
     ->  y = 2 (x + 3)|^2 - 12
   - [ ] Distribute and merge should operate contextually.
   - [ ] Always show entry at point in "big" mode, somewhere.
   - [ ] Move all options to unified configuration view.
     - Free up option prefix bindings (eg, m).
   - [ ] Rebind +, -, negate, negative commands. Since these are used very
     frequently, make them easily accessible.
   - [ ] Feature: In stack mode, bind M-[n/p] to recall previous/next bare
     (starting from empty) edit-mode entries. The purpose of this is to avoid the
     pattern of having to duplicate or store an entry that you might want to
     reuse or recall in case you screw up a calculation.

* Bugs
** BUG (my/calc-backward-noun) and (my/calc-forward-noun) should ignore line prefix.

* BACKLOG
** Issue: j D (my/calc-sel-distribute)
   Doesn't work contextually. Should work like 'j M'. Work on stack item when at home.
** Instead of having to use the default bindings 'a m &', can you make 'a m o' work?
   This should invert both sides of an equation. Normally the binding would use
   '&' instead of 'o', but 'o' is more convenient and I have that bound to
   'calc-inv' The issue is that the 'a m' sequence expects standard keybindings.

* Package
  Binding for "home"
  Args buffer
  Config file with all config settings and default values
   calx: calc with alternative ux
  How to use macro with def math
  Alternative graphing
  Alternative trail. Should support time travel and finding old single entries.
  Use transient mode for prefix commands
  Swap _ and -
  Show all formulas buffer

* Questions
  - [ ] In binary command should subject and args be taken from stack (m and
    m + 1)? Current (maf-equal-to) works like this and it seems to make sense.

* Cleanup
  - [ ] Delete my/calc
  - [ ] Use stock bindings
  - [ ] Generate tests to cover maf. step tests when testing end-to-end. unit
    tests for basic stuff.
